### ISSUE TITLE
"qsub -I" should not silenty ignore unused arguments

### ISSUE THREAD

**Issue by boegel** [hpcugent/slurm-torque-wrappers#12]
Using this command (silently) results in undesired behavior:

```
qsub -I nodes=1:ppn=2 --debug
DEBUG: Generated interactive  command '/usr/bin/salloc -J INTERACTIVE --nodes=1 /usr/bin/srun --pty --mem-per-cpu=0 --chdir=/user/gent/430/vsc43020 --cpu-bind=v,none --export=USER,HOME,TERM /usr/bin/bash -i -l'
```

Note that there are no `--ntasks` or `--tasks-per-node` options being passed to `salloc`.

The problem here is that there's a missing `-l`, the correct command is `qsub -I -l nodes=1:ppn=2`.

Basically without using `-l`, the `nodes=1:ppn=2` gets ignored silently (and it doesn't get passed to `salloc` either).

Either `qsub` should fail, or it should pass arguments to `salloc` (which would then fail because passing `nodes=1:ppn=2` does not make sense).

**Comment by stdweird** [comment]
there's no "misisng -l", the `-I` shouldn't accept any arguments (or gobble up the next argument).
the "correct" behaviour of the command is to pass `nodes=2 ...` as executable/script name in the example above

**Comment by stdweird** [comment]
what is the behaviour of `qsub -I somebinary` in torque? if it is an error, it should fail also here
the command `nodes=...` is ignored because this is an interactive job. 
i don't think we should support to somehow start the interactive job with the passed command, so an error is appropriate:
https://github.com/hpcugent/slurm-torque-wrappers/blob/master/files/qsub.pl#L452
befroe `$script` is reassigned, it should be checkd if it empty or not. if it is not empty, die with some message

**Comment by boegel** [comment]
I agree, just errorring out makes sense here. That's also what Torque does in this exact situation:

```
$ qsub -I nodes=1:ppn=5
qsub: script file 'nodes=1:ppn=5' cannot be loaded - No such file or directory
```

**Comment by hajgato** [comment]
It needs a bit more attention, because with `SLURM` you could run scripts interactive as well (in contrast to `Torque`. So `srun --pty /usr/bin/python` or `srun --pty ./script` are valid. So simply passing `nodes=1:ppn=5` as a script file will not fail `SLURM` immediately (as it failed `Torque`), only when the script would start (and it does not exist). 

So at the end, the wrapper should hard fail those cases, and do not give the users the possibility to run scripts interactively (via the wrapper).

**Comment by boegel** [comment]
@hajgato The wrappers should not support using `qsub -I` to run a script interactively, since it's supposed to mimic Torque.

So if an argument is passed to `qsub -I`, it should fail hard on that (rather than silently ignore it).
