### ISSUE TITLE
"qsub -I -X" not supported in Slurm 'qsub' wrapper

### ISSUE THREAD

**Issue by boegel** [hpcugent/slurm-torque-wrappers#14]
```
$ qsub -I -X
Unknown option: X
```

This should be trivial to add, since this passing `--x11=first` to `sbatch` equivalent with the `-X` option for `qsub`.

X11 forwarding needs to be enabled in the Slurm configuration too though via `PrologFlags=X11`:

```
$ qsub -I --pass=x11=first
salloc: error: No DISPLAY variable set, cannot setup x11 forwarding.
```

(see also https://slurm.schedmd.com/slurm.conf.html and https://bugs.schedmd.com/show_bug.cgi?id=4721)

**Comment by stdweird** [comment]
we should wonder if this is worth it (an easy way to run eg x2go on the nodes etc is much more interesting/performant)

**Comment by boegel** [comment]
Either we should support it, or we should make `qsub -I -X` print a message that informs users to use `x2go` instead (with a pointer to the documentation).

**Comment by boegel** [comment]
Not being able to log into a Slurm workernode with X11 forwarding enabled is quite annoying, we're hitting this problem right now during the OpenMP training session...

@itkovian Are there any big concerns with changing to Slurm configuration to set `PrologFlags=X11`?

**Comment by hajgato** [comment]
To enable x11 forwarding with slurm, `PrologFlags=x11` should be added to `slurm.conf`

**Comment by hajgato** [comment]
Running `qsub -I -X` will not work from `X2Go` session. (So `X2Go` to login node, then `X11Forwarding` from the worker node to the login node) in one go. Because `X2Go` display is a "local" display, and it is not network accessible. (You can use a workaround `ssh -X localhost`, though.)

**Comment by alvarosimon** [comment]
We have a new ticket from an user asking for this. We should find the best option for the users (and change the current documentation). A workaround for now is just start the x2go session as usual, execute `qsub -I` and then as @hajgato said `ssh -X` to the worker node provided by the slurm interactive job. That works

**Comment by stdweird** [comment]
no, that is horrible.

**Comment by boegel** [comment]
@hajgato Isn't there a setting in X2Go to fix that? What makes it a "local" display? Local is what sense? That's a bit weird...

**Comment by alvarosimon** [comment]
yes it is horrible but it works, but in any case we should allow the qsub -X option

**Comment by stdweird** [comment]
google, try it sometime? http://lists.x2go.org/pipermail/x2go-user/2013-December/001843.html
(but this is an old thread, not sure how relevant)

so disabled by default for security reasons

**Comment by alvarosimon** [comment]
@stdweird that is an option, but not sure how insecure that could be....
We can change that just updating `/etc/x2go/x2goagent.options` from quattor

**Comment by stdweird** [comment]
to be clear, i would not enable it by default; just see how the user could use it

**Comment by alvarosimon** [comment]
it seems that you can override these options from the client side (but it is not documented). @hajgato `qsub -X` it is enabled in banette? maybe we should try this there

**Comment by hajgato** [comment]
We have 3 possible ways:
a) We fix the X11 forwarding: I can fix qsub wrapper, but we have to change `slurm.conf` as well. (Right now it does not work with native slurm). I would not encourage this usage, but this would be the most comfortable to the users. (although users need X-Windows on windows)
b) We fix X2Go 'local display' issue, then users can use X2Go to the login node (RDP protocol between users' computer and login node), and from the login node to the worker node X11forwarding. It is a hybrid version, not sure that we want to push this. (although we might have enough bandwidth between login and worker nodes). I have no idea about the security concerns enabling network access to the X2Go display. In my opinion, this would be the best solution for the user. (comfort/quality ratio). This requires a working a). This requires an X2Go client installation on the user side)
c) We use the current workaround: start an interactive job on a worker node, and connect to the worker node with X2Go. In this case RDP protocol is used between users' computer and worker node.  This solution would give the best result (quality wise), but not the most comfortable for the users. This require an X2Go installation on the user side.

@alvarosimon there is no qsub on banette. use `srun --pty --x11 /bin/bash`. This is close enough to `qsub -I -X`. (Fixing qsub-wrapper to understand -X is a one-liner. But I did not want to do that until we agree what should happen, because the solution depends on what we decide.) All in all, we have to modify `slurm.conf` to make X11 forwarding to work.

**Comment by stdweird** [comment]
@hajgato what do you mean with "no qsub on banette"? you can submit from the loginnodes, no?

i would go for solution b (as it is an actual solution), but defintely not enable the tcp by default. most x2go users do not need x11 forwarding imho

**Comment by hajgato** [comment]
I have read about solution b). I would not do that. enabling network access requires users to use `xhost` command, and wrongly used xhost command `xhost +` gives access to everyone to the display and clipboard. You could read passwords, or sniff screens. Properly configured xhost (`xhost -& xhost +$USER`), might be not good enough, as it from the '90s. In this case xauth and MAGIC COOKIES (which is the current solution) are not used.

@stdweird Its not so simple, as the login node and the worker node must  have the same slurm.config, and in case of banette it is not true. So we might get unexpected results. (plus srun --x11 does not work from the login nodes....)

**Comment by hajgato** [comment]
@stdweird You mean you would not go for b). Only for a) and c), right? As b) describes when X2Go users need X11forwarding.

**Comment by hajgato** [comment]
@stdweird @alvarosimon Yeah, I forget to mention that you should submit `srun --x11`... from node280{1,8} or from master23.

**Comment by alvarosimon** [comment]
Ok about x2go I did a quick test, I have installed x2go in master23 (with
`-nolisten tcp` option) and it works with srun -x11 but you should set the
DISPLAY variable correctly.

[image: Screenshot_20190424_162325.png]

**Comment by hajgato** [comment]
@alvarosimon Not sure about how secure running X2Go without `-nolisten tcp` option.

**Comment by alvarosimon** [comment]
also you do not have to start the full xfce env, just a xterm is enough.
https://send.firefox.com/download/3242714858dee2c0/#r7NrHl_rwNOyx51USTtv2w

About the nolisten tcp option they have more info here:
https://wiki.x2go.org/doku.php/wiki:security:start
